# Generated by Django 3.2 on 2022-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsletterusers',
            options={'verbose_name_plural': 'Newsletter Users'},
        ),
        migrations.AlterField(
            model_name='newsletterusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
