# Generated by Django 3.2 on 2022-08-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220818_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='mugs',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
