# Generated by Django 3.2 on 2022-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mugs_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mugs',
            name='slug_name',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
